# Generated by Django 5.2.1 on 2025-05-21 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionablePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=128)),
                ('pattern_type', models.CharField(choices=[('word', 'Word'), ('phrase', 'Phrase'), ('regex', 'Regular Expression')], default='word', max_length=16)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('priority', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=256, unique=True)),
                ('subject', models.CharField(max_length=512)),
                ('body_preview', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_actionable', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('web_link', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('actionable_patterns', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(blank=True, max_length=16)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mainApp.processedemail')),
            ],
        ),
    ]
