# Generated by Django 5.2.1 on 2025-05-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionablePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=128)),
                ('pattern_type', models.CharField(choices=[('word', 'Word'), ('phrase', 'Phrase'), ('regex', 'Regular Expression')], default='word', max_length=16)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('priority', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
