# Generated by Django 5.2.1 on 2025-05-20 02:20

from django.db import migrations

def seed_actionable_patterns(apps, schema_editor):
    ActionablePattern = apps.get_model('mainApp', 'ActionablePattern')
    patterns = [
        {"pattern": "ASAP", "pattern_type": "word", "priority": "Urgent"},
        {"pattern": "action item", "pattern_type": "phrase", "priority": ""},
        {"pattern": "action required", "pattern_type": "phrase", "priority": "Urgent"},
        {"pattern": "address", "pattern_type": "word", "priority": ""},
        {"pattern": "analyze", "pattern_type": "word", "priority": ""},
        {"pattern": "approve", "pattern_type": "word", "priority": ""},
        {"pattern": "arrange", "pattern_type": "word", "priority": ""},
        {"pattern": "assign", "pattern_type": "word", "priority": ""},
        {"pattern": "attend", "pattern_type": "word", "priority": ""},
        {"pattern": "book", "pattern_type": "word", "priority": ""},
        {"pattern": "by end of day", "pattern_type": "phrase", "priority": "Urgent"},
        {"pattern": r"by (?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)", "pattern_type": "regex", "priority": "Urgent"},
        {"pattern": "cancel", "pattern_type": "word", "priority": ""},
        {"pattern": "collect", "pattern_type": "word", "priority": ""},
        {"pattern": "complete", "pattern_type": "word", "priority": ""},
        {"pattern": "confirm", "pattern_type": "word", "priority": ""},
        {"pattern": "deadline", "pattern_type": "word", "priority": ""},
        {"pattern": r"(deadline|due|before) [\w\s,]+", "pattern_type": "regex", "priority": "Important"},
        {"pattern": "delegate", "pattern_type": "word", "priority": ""},
        {"pattern": "draft", "pattern_type": "word", "priority": ""},
        {"pattern": "due date", "pattern_type": "phrase", "priority": ""},
        {"pattern": r"due (\d{1,2}/\d{1,2}/\d{2,4})", "pattern_type": "regex", "priority": "Important"},
        {"pattern": "end of week", "pattern_type": "phrase", "priority": ""},
        {"pattern": "fill", "pattern_type": "word", "priority": ""},
        {"pattern": "finalize", "pattern_type": "word", "priority": ""},
        {"pattern": "fix", "pattern_type": "word", "priority": ""},
        {"pattern": "follow up", "pattern_type": "phrase", "priority": ""},
        {"pattern": r"follow[- ]?up", "pattern_type": "regex", "priority": ""},
        {"pattern": "for your approval", "pattern_type": "phrase", "priority": ""},
        {"pattern": "for your information", "pattern_type": "phrase", "priority": ""},
        {"pattern": "get back to me", "pattern_type": "phrase", "priority": ""},
        {"pattern": "input", "pattern_type": "word", "priority": ""},
        {"pattern": "let me know", "pattern_type": "phrase", "priority": ""},
        {"pattern": "needs your attention", "pattern_type": "phrase", "priority": "Urgent"},
        {"pattern": "next steps", "pattern_type": "phrase", "priority": ""},
        {"pattern": "no later than", "pattern_type": "phrase", "priority": "Urgent"},
        {"pattern": "organize", "pattern_type": "word", "priority": ""},
        {"pattern": "plan", "pattern_type": "word", "priority": ""},
        {"pattern": "please advise", "pattern_type": "phrase", "priority": ""},
        {"pattern": "please confirm", "pattern_type": "phrase", "priority": ""},
        {"pattern": "prepare", "pattern_type": "word", "priority": ""},
        {"pattern": "process", "pattern_type": "word", "priority": ""},
        {"pattern": "provide", "pattern_type": "word", "priority": ""},
        {"pattern": "remind", "pattern_type": "word", "priority": ""},
        {"pattern": "report", "pattern_type": "word", "priority": ""},
        {"pattern": "request", "pattern_type": "word", "priority": ""},
        {"pattern": "reply", "pattern_type": "word", "priority": ""},
        {"pattern": "reschedule", "pattern_type": "word", "priority": ""},
        {"pattern": "respond", "pattern_type": "word", "priority": ""},
        {"pattern": "review", "pattern_type": "word", "priority": ""},
        {"pattern": "schedule", "pattern_type": "word", "priority": ""},
        {"pattern": "send", "pattern_type": "word", "priority": ""},
        {"pattern": "share", "pattern_type": "word", "priority": ""},
        {"pattern": "sign", "pattern_type": "word", "priority": ""},
        {"pattern": "submit", "pattern_type": "word", "priority": ""},
        {"pattern": r"submit.*by [\w ]+", "pattern_type": "regex", "priority": "Urgent"},
        {"pattern": "take action", "pattern_type": "phrase", "priority": ""},
        {"pattern": "to do", "pattern_type": "phrase", "priority": ""},
        {"pattern": "update", "pattern_type": "word", "priority": ""},
        {"pattern": "urgent", "pattern_type": "word", "priority": "Urgent"},
        {"pattern": "verify", "pattern_type": "word", "priority": ""},
        {"pattern": "within (\\d+) (hours?|days?)", "pattern_type": "regex", "priority": "Urgent"},
        {"pattern": "your response is required", "pattern_type": "phrase", "priority": "Urgent"},
    ]
    for entry in patterns:
        ActionablePattern.objects.get_or_create(
            pattern=entry["pattern"],
            pattern_type=entry["pattern_type"],
            defaults={
                "priority": entry["priority"],
                "is_active": True
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_actionable_patterns),
    ]
