# Generated by Django 5.2.1 on 2025-05-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20250520_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=256, unique=True)),
                ('subject', models.CharField(max_length=512)),
                ('body_preview', models.TextField()),
                ('actionable_patterns', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(blank=True, max_length=16)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=256, unique=True)),
                ('subject', models.CharField(max_length=512)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_actionable', models.BooleanField(default=False)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to='mainApp.extractedtask')),
            ],
        ),
    ]
