# Generated by Django 5.2.1 on 2025-05-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_seed_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinktaskeruser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
