# Generated by Django 5.2.1 on 2025-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_extractedtask_processedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
