# Generated by Django 5.2.1 on 2025-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_processedemail_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='web_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
