# Generated by Django 5.2.1 on 2025-05-22 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_extractedtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedtask',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mainApp.processedemail'),
        ),
    ]
