# Generated by Django 5.2.1 on 2025-05-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_extractedtask_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtask',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
