# Generated by Django 5.2.1 on 2025-05-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_extractedtask_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinktaskeruser',
            name='last_synced_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
