# Generated by Django 5.2.1 on 2025-05-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_thinktaskeruser_last_synced_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
