from django.db import migrations

def add_patterns(apps, schema_editor):
    ActionablePattern = apps.get_model('mainApp', 'ActionablePattern')
    patterns = [
        {"pattern": "ASAP", "pattern_type": "word", "priority": ""},
        {"pattern": "action item", "pattern_type": "phrase", "priority": ""},
        {"pattern": "action required", "pattern_type": "phrase", "priority": ""},
        {"pattern": "address", "pattern_type": "word", "priority": ""},
        {"pattern": "analyze", "pattern_type": "word", "priority": ""},
        {"pattern": "approve", "pattern_type": "word", "priority": ""},
        {"pattern": "arrange", "pattern_type": "word", "priority": ""},
        {"pattern": "assign", "pattern_type": "word", "priority": ""},
        {"pattern": "attend", "pattern_type": "word", "priority": ""},
        {"pattern": "book", "pattern_type": "word", "priority": ""},
        {"pattern": "by end of day", "pattern_type": "phrase", "priority": "Urgent"},
        {"pattern": r"by (?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)", "pattern_type": "regex", "priority": ""},
        {"pattern": "cancel", "pattern_type": "word", "priority": ""},
        {"pattern": "collect", "pattern_type": "word", "priority": ""},
        {"pattern": "complete", "pattern_type": "word", "priority": ""},
        {"pattern": "confirm", "pattern_type": "word", "priority": ""},
        {"pattern": "create", "pattern_type": "word", "priority": ""},
        {"pattern": "deadline", "pattern_type": "word", "priority": ""},
        {"pattern": r"(deadline|due|before) [\w\s,]+", "pattern_type": "regex", "priority": ""},
        {"pattern": "delegate", "pattern_type": "word", "priority": ""},
        {"pattern": "draft", "pattern_type": "word", "priority": ""},
        {"pattern": "due date", "pattern_type": "phrase", "priority": ""},
        {"pattern": r"due (\d{1,2}/\d{1,2}/\d{2,4})", "pattern_type": "regex", "priority": ""},
        {"pattern": "end of week", "pattern_type": "phrase", "priority": ""},
        {"pattern": "fill", "pattern_type": "word", "priority": ""},
        {"pattern": "finalize", "pattern_type": "word", "priority": ""},
        {"pattern": "fix", "pattern_type": "word", "priority": ""},
        {"pattern": "follow up", "pattern_type": "phrase", "priority": ""},
        {"pattern": r"follow[- ]?up", "pattern_type": "regex", "priority": ""},
        {"pattern": "for your approval", "pattern_type": "phrase", "priority": ""},
        {"pattern": "for your information", "pattern_type": "phrase", "priority": ""},
        {"pattern": "get back to me", "pattern_type": "phrase", "priority": ""},
        {"pattern": "input", "pattern_type": "word", "priority": ""},
        {"pattern": "let me know", "pattern_type": "phrase", "priority": ""},
        {"pattern": "needs your attention", "pattern_type": "phrase", "priority": "Urgent"},
        {"pattern": "next steps", "pattern_type": "phrase", "priority": ""},
        {"pattern": "no later than", "pattern_type": "phrase", "priority": "Urgent"},
        {"pattern": "organize", "pattern_type": "word", "priority": ""},
        {"pattern": "plan", "pattern_type": "word", "priority": ""},
        {"pattern": "please advise", "pattern_type": "phrase", "priority": ""},
        {"pattern": "please confirm", "pattern_type": "phrase", "priority": ""},
        {"pattern": "prepare", "pattern_type": "word", "priority": ""},
        {"pattern": "process", "pattern_type": "word", "priority": ""},
        {"pattern": "provide", "pattern_type": "word", "priority": ""},
        {"pattern": "remind", "pattern_type": "word", "priority": ""},
        {"pattern": "report", "pattern_type": "word", "priority": ""},
        {"pattern": "request", "pattern_type": "word", "priority": ""},
        {"pattern": "reply", "pattern_type": "word", "priority": ""},
        {"pattern": "reschedule", "pattern_type": "word", "priority": ""},
        {"pattern": "respond", "pattern_type": "word", "priority": ""},
        {"pattern": "review", "pattern_type": "word", "priority": ""},
        {"pattern": "schedule", "pattern_type": "word", "priority": ""},
        {"pattern": "send", "pattern_type": "word", "priority": ""},
        {"pattern": "share", "pattern_type": "word", "priority": ""},
        {"pattern": "sign", "pattern_type": "word", "priority": ""},
        {"pattern": "submit", "pattern_type": "word", "priority": ""},
        {"pattern": r"submit.*by [\w ]+", "pattern_type": "regex", "priority": ""},
        {"pattern": "take action", "pattern_type": "phrase", "priority": ""},
        {"pattern": "to do", "pattern_type": "phrase", "priority": ""},
        {"pattern": "update", "pattern_type": "word", "priority": ""},
        {"pattern": "urgent", "pattern_type": "word", "priority": ""},
        {"pattern": "verify", "pattern_type": "word", "priority": ""},
        {"pattern": "within (\\d+) (hours?|days?)", "pattern_type": "regex", "priority": ""},
        {"pattern": "your response is required", "pattern_type": "phrase", "priority": ""},        
        {"pattern": "investigate", "pattern_type": "word", "priority": ""},
        {"pattern": "troubleshoot", "pattern_type": "word", "priority": ""},
        {"pattern": "debug", "pattern_type": "word", "priority": ""},
        {"pattern": "log file", "pattern_type": "phrase", "priority": ""},
        {"pattern": "build", "pattern_type": "word", "priority": ""},
        {"pattern": "test", "pattern_type": "word", "priority": ""},
        {"pattern": "ticket", "pattern_type": "word", "priority": ""},
        {"pattern": "SRMS record", "pattern_type": "phrase", "priority": ""},
        {"pattern": "rename", "pattern_type": "word", "priority": ""},
        {"pattern": "replace", "pattern_type": "word", "priority": ""},
        {"pattern": "mismatch", "pattern_type": "word", "priority": ""},
        {"pattern": "deletion", "pattern_type": "word", "priority": ""},
        {"pattern": "proceed with deletion", "pattern_type": "phrase", "priority": ""},
        {"pattern": "coordinate", "pattern_type": "word", "priority": ""},
        {"pattern": "review the status", "pattern_type": "phrase", "priority": ""},
        {"pattern": "status update", "pattern_type": "phrase", "priority": ""},
        {"pattern": "weekly sync", "pattern_type": "phrase", "priority": ""},
        {"pattern": "reminder", "pattern_type": "word", "priority": ""},
        {"pattern": "assign", "pattern_type": "word", "priority": ""},
        {"pattern": "critical", "pattern_type": "word", "priority": ""},
        {"pattern": "regression", "pattern_type": "word", "priority": ""},
        {"pattern": "immediate attention", "pattern_type": "phrase", "priority": ""},
        {"pattern": "submit your test results", "pattern_type": "phrase", "priority": ""},
        {"pattern": "include any issues", "pattern_type": "phrase", "priority": ""},
        {"pattern": "meeting", "pattern_type": "word", "priority": ""},
        {"pattern": "demo", "pattern_type": "word", "priority": ""},
        {"pattern": "documentation", "pattern_type": "word", "priority": ""},
        {"pattern": "readme", "pattern_type": "word", "priority": ""},
        {"pattern": "section", "pattern_type": "word", "priority": ""},
        {"pattern": "revise", "pattern_type": "word", "priority": ""},
        {"pattern": "additional troubleshooting tips", "pattern_type": "phrase", "priority": ""},
        {"pattern": "replacement", "pattern_type": "word", "priority": ""},
        {"pattern": "procurement", "pattern_type": "word", "priority": ""},
        {"pattern": "schedule", "pattern_type": "word", "priority": ""},
        {"pattern": "update the ticket", "pattern_type": "phrase", "priority": ""},
        {"pattern": "test results", "pattern_type": "phrase", "priority": ""},
        {"pattern": "report an issue", "pattern_type": "phrase", "priority": ""},
        {"pattern": "issue found", "pattern_type": "phrase", "priority": ""},
        {"pattern": "fix this issue", "pattern_type": "phrase", "priority": ""},
        {"pattern": "review and approve", "pattern_type": "phrase", "priority": ""},
        {"pattern": "escalate", "pattern_type": "word", "priority": ""},
        {"pattern": "authorize", "pattern_type": "word", "priority": ""},
        {"pattern": "feedback required", "pattern_type": "phrase", "priority": ""},
        {"pattern": "pending your approval", "pattern_type": "phrase", "priority": ""},
        {"pattern": r"by [A-Za-z]+ \d{1,2}", "pattern_type": "regex", "priority": ""},
        {"pattern": "for immediate action", "pattern_type": "phrase", "priority": ""},
        {"pattern": "join the call", "pattern_type": "phrase", "priority": ""},
        {"pattern": "arrange meeting", "pattern_type": "phrase", "priority": ""},
        {"pattern": "contact support", "pattern_type": "phrase", "priority": ""},
        {"pattern": "summarize", "pattern_type": "word", "priority": ""},
        {"pattern": "edit", "pattern_type": "word", "priority": ""},
        {"pattern": "revert", "pattern_type": "word", "priority": ""},
        {"pattern": "initiate", "pattern_type": "word", "priority": ""},
    ]

    for p in patterns:
        ActionablePattern.objects.get_or_create(
            pattern=p["pattern"],
            pattern_type=p["pattern_type"],
            defaults={"priority": p.get("priority", ""), "is_active": p.get("is_active", True)},
        )

class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0010_referencedocument'),
    ]

    operations = [
        migrations.RunPython(add_patterns),
    ]
