# Generated by Django 5.2.1 on 2025-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_add_actionable_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtask',
            name='planner_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='extractedtask',
            name='todo_task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
