# Generated by Django 5.2.1 on 2025-05-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_extractedtask_planner_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedtask',
            name='planner_task_id',
        ),
    ]
