# Generated by Django 5.2.1 on 2025-05-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_remove_extractedtask_planner_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtask',
            name='todo_list_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
