# Generated by Django 5.2.1 on 2025-06-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_extractedtask_todo_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='to_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
