# Generated by Django 5.2.1 on 2025-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_processedemail_to_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedtask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
