# Generated by Django 5.2.1 on 2025-06-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_extractedtask_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtask',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
    ]
