# Generated by Django 5.2.1 on 2025-06-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_extractedtask_is_delayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedtask',
            name='todo_list_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='extractedtask',
            name='todo_task_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
